### ISSUE TITLE
following closely + questions

### ISSUE THREAD

**Issue by david-kutas** [bruno-j-nicoletti/SkiaWebBind#1]
I'm following closely the development of this library and cheering from the sideline. This is very important work.

I have two questions:

1. will you have a tutorial/installation guides to start working with this lib?
2. are you gonna support vector based text rendering? such as: https://github.com/azsn/gllabel

**Comment by bruno-j-nicoletti** [comment]
Thanks for the interest. 

I'm working on this in my spare time, so it may take a while to get there and I keep hitting issues. For example the current version of emscripten [is broken so you can't use pthreads
](https://github.com/emscripten-core/emscripten/issues/22989)

If I manage to succeed I'll definitely write up a how-to. 

My main goal is to just to get Skia working in the browser from a C++ application compiled to web assembly, getting other libraries working is out of scope.
